// Comparison Report - Generated by Soak
// This template uses variables injected by the Python exporter

#set document(
  title: "{{ comparison_name|e }} - Comparison Report",
  author: "Soak v{{ version }}",
)

#set page(
  paper: "a4",
  margin: (x: 2cm, y: 2.5cm),
  header: context {
    if counter(page).get().first() > 1 [
      #text(size: 9pt, fill: gray)[{{ comparison_name|e }} -- Comparison Report]
      #h(1fr)
      #text(size: 9pt, fill: gray)[Page #counter(page).display()]
    ]
  },
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
)

#set heading(numbering: "1.")

#set par(justify: true)

// Title page
#align(center)[
  #v(3cm)
  #text(size: 24pt, weight: "bold")[Comparison Report]
  #v(0.5cm)
  #text(size: 14pt)[{{ comparison_name|e }}]
  #v(1cm)
  #text(size: 12pt)[
    {{ run_a_name|e }} ({{ theme_count_a }} themes) \
    vs \
    {{ run_b_name|e }} ({{ theme_count_b }} themes)
  ]
  #v(2cm)

  #table(
    columns: 2,
    stroke: none,
    align: (right, left),
    [*Computed:*], [{{ completed_at }}],
    [*Embedding model:*], [{{ embedding_model|e }}],
    [*Calibrated:*], [{{ "Yes" if use_calibrated else "No" }}],
    [*OT entropy (k):*], [{{ ot_entropy_k }}],
  )

  #v(1cm)
  #line(length: 50%, stroke: 0.5pt + gray)
  #v(0.5cm)
  #box[
    #image("soak-logo.svg", height: 24pt)
    #h(0.5em)
    #link("{{ github_url }}")[#text(size: 10pt, fill: gray)[Soak v{{ version }}]]
  ]
]

#pagebreak()

// Summary metrics
= Summary Metrics

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*OT Alignment*], [{{ "%.2f"|format(alignment) }} #text(fill: gray, size: 9pt)[(1 - cost, higher = better)]],
  [*OT Cost*], [{{ "%.3f"|format(ot_cost) }} #text(fill: gray, size: 9pt)[(lower = better)]],
  [*Fidelity*], [{{ "%.2f"|format(fidelity) }} #text(fill: gray, size: 9pt)[(harmonic mean of directional similarities)]],
  [*Strong Couplings*], [{{ strong_matches }} pairs #text(fill: gray, size: 9pt)[(similarity > 0.7)]],
)

#v(1cm)

{% if has_sankey_image %}
= Theme Alignment

#figure(
  image("{{ sankey_image_path }}", width: 100%),
  caption: [Optimal transport flow between themes. Green indicates good alignment (similarity > 0.7), red indicates poor alignment.],
)
{% endif %}

// Theme pairings
= Theme Pairings

The following table shows the best-matched theme pairs, sorted by similarity score.

#table(
  columns: (auto, 1fr, 1fr, auto),
  stroke: 0.5pt + gray,
  align: (center, left, left, center),
  [*Rank*], [*{{ run_a_name|e }}*], [*{{ run_b_name|e }}*], [*Similarity*],
  {% for match in matches[:20] %}
  [{{ loop.index }}], [{{ match.theme_a[:40]|capitalize|e }}], [{{ match.theme_b[:40]|capitalize|e }}], [{{ "%.2f"|format(match.similarity) }}],
  {% endfor %}
)
{% if matches | length > 20 %}
#text(fill: gray)[... and {{ matches | length - 20 }} more pairs]
{% endif %}

{% if has_heatmap_image %}
#pagebreak()
= Similarity Matrix

#figure(
  image("{{ heatmap_image_path }}", width: 100%),
  caption: [{{ "Calibrated" if use_calibrated else "Raw" }} similarity matrix between themes. Brighter colours indicate higher similarity.],
)
{% endif %}

// Detailed metrics
#pagebreak()
= Detailed Metrics

== Coverage (Hit Rates)

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*Hit Rate {{ run_a_name|e }}*], [{{ "%.1f%%"|format(hit_rate_a * 100) }} #text(fill: gray, size: 9pt)[(themes with >= 1 match above threshold)]],
  [*Hit Rate {{ run_b_name|e }}*], [{{ "%.1f%%"|format(hit_rate_b * 100) }}],
  [*Jaccard*], [{{ "%.3f"|format(jaccard) }} #text(fill: gray, size: 9pt)[(proportion of pairs above threshold)]],
)

== Fidelity (Mean Best-Match Similarity)

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*{{ run_a_name|e }} -> {{ run_b_name|e }}*], [{{ "%.3f"|format(mean_max_sim_a_to_b) }}],
  [*{{ run_b_name|e }} -> {{ run_a_name|e }}*], [{{ "%.3f"|format(mean_max_sim_b_to_a) }}],
  [*Fidelity (harmonic mean)*], [{{ "%.3f"|format(fidelity) }}],
)

== Hungarian Matching (Optimal 1-to-1 Assignment)

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*Coverage {{ run_a_name|e }}*], [{{ "%.1f%%"|format(hungarian_coverage_a * 100) }}],
  [*Coverage {{ run_b_name|e }}*], [{{ "%.1f%%"|format(hungarian_coverage_b * 100) }}],
  [*1-to-1 Jaccard*], [{{ "%.3f"|format(hungarian_jaccard) }} #text(fill: gray, size: 9pt)[(matched pairs / total unique)]],
)

== Optimal Transport

K = {{ ot_entropy_k }}

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*Shared Mass*], [{{ "%.1f%%"|format(shared_mass * 100) }}],
  [*Semantic Alignment*], [{{ "%.1f%%"|format(alignment * 100) }}],
  {% if paraphrase_ceiling %}[*Paraphrase Ceiling*], [{{ "%.1f%%"|format(paraphrase_ceiling * 100) }}],{% endif %}
  {% if null_floor %}[*Word-salad Floor*], [{{ "%.1f%%"|format(null_floor * 100) }}],{% endif %}
)

// Methods section
#pagebreak()
= Methods

{{ methods_text|md }}

// Configuration
= Comparison Configuration

#table(
  columns: 2,
  stroke: (x: none, y: 0.5pt + gray),
  align: (right, left),
  [*Embedding model*], [{{ embedding_model|e }}],
  [*Embedding template*], [{{ embedding_template|e }}],
  [*Similarity threshold*], [{{ similarity_threshold }}],
  [*OT entropy (k)*], [{{ ot_entropy_k }}],
  [*Calibrated*], [{{ "Yes" if use_calibrated else "No" }}],
)
