name: demo
extra_context:
  persona: Winston
steps:
- split:
    name: chunks
    template_text: chunks
- batch:
    name: batches
    inputs:
    - chunks
    batch_size: 3
- reduce:
    name: reduced_batches
    inputs:
    - batches
    template_text: reduced_batches
- map:
    name: threewordsummaries
    inputs:
    - reduced_batches
    model_name: gpt-4o
    template_text: threewordsummaries
- reduce:
    name: joinedsummaries
    inputs:
    - threewordsummaries
    template_text: joinedsummaries
- transform:
    name: narrative_report
    inputs:
    - joinedsummaries
    template_text: narrative_report

--- {# chunks }

{{input}}


--- {# reduced_batches }

{{input}}


--- {# threewordsummaries }

{{input}} summarise in 3 words: [[output]]


--- {# joinedsummaries }

{{input}}\n\n---\n\n


--- {# narrative_report }

{{input}}

 make this into a haikiu
 [[poem:poem]]

